spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/papermatedb
    username: papermate
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      
logging:
  level:
    com.papermate: DEBUG
